In [ ]:
import numpy as np
import sympy as sp
from typing import List
import numpy.linalg as la
# Finite Difference
# method:
#     0: Forward
#     1: Backward
#     2: Central


# 1-D x, return df
# 导数精确值
def diff_single(f,x0:float):
  return f.diff(x,1).subs(x,x0)

# 1-D x, return df approximation (FD)
# 导数估算值, Finite difference
# method:
#     0: Forward
#     1: Backward
#     2: Central
def FD_single(f, x0:float, h:float,method: int):
  if(method==0):
    return (f.subs(x,x0+h)-f.subs(x,x0))/h
  if(method==1):
    return (f.subs(x,x0)-f.subs(x,x0-h))/h
  return (f.subs(x,x0+h)-f.subs(x,x0-h))/(2*h)


# 1-D x, return absolute error of FFD
# Absolute error, 一维
# method:
#     0: Forward
#     1: Backward
#     2: Central
def FD_error_abs(f, x0:float, h:float,method: int):
  return np.abs(FD_single(f, x0, h,method)-diff_single(f,x0))

# 1-D x, return relative error of FFD
# Relative error, 一维
# method:
#     0: Forward
#     1: Backward
#     2: Central
def FD_error_rel(f, x0:float, h:float,method: int):
  return np.abs(FD_error_abs(f, x0, h,method)/diff_single(f,x0))


# n-D x, return df
# 导数精确值, n维, x:[f的symbol,按x1,x2,x3..排]
def diff_multi(f,x0:np.ndarray, x:List[sp.core.symbol.Symbol])->np.ndarray:
  df = []
  for var in x:
    df.append(f.diff(var,1))
  for i in range(len(df)):
    for j in range(len(x)):
      df[i] = df[i].subs(x[j], x0[j])
  return np.array(df)

# n-D x, return df
# 导数估算值, n维, x:[f的symbol,按x1,x2,x3..排], x0为各项xi的初始值
# method:
#     0: Forward
#     1: Backward
#     2: Central
def FD_multi(f,x0:np.ndarray, x:List[sp.core.symbol.Symbol], h:float, method: int)->np.ndarray:
  fx = f
  for i in range(len(x)):
    fx = fx.subs(x[i], x0[i])
  f_fd = []
  for i in range(len(x)):
    xh0 = np.copy(x0)
    xh1 = np.copy(x0)
    xh0[i] += h
    xh1[i] -= h

    dfi = 0
    dfi0 = f
    dfi1 = f
    for j in range(len(x0)):
      dfi0 = dfi0.subs(x[j], xh0[j])
      dfi1 = dfi1.subs(x[j], xh1[j])
    if(method==0): dfi = (dfi0-fx)/h
    elif(method==1): dfi = (fx-dfi1)/h
    else: dfi = (dfi0-dfi1)/(2*h)
    f_fd.append(dfi)
  return np.array(f_fd)

# n-D x, return error
# Error, n维, x:[f的symbol,按x1,x2,x3..排], x0为各项xi的初始值
# method:
#     0: Forward
#     1: Backward
#     2: Central
def FD_multi_Error(f,x0:np.ndarray, x:List[sp.core.symbol.Symbol], h:float, method: int)->int:
  f_approx = FD_multi(f,x0,x,h,method)
  df = diff_multi(f,x0,x)
  return (la.norm(f_approx-df,np.inf))
  

print("======== EXAMPLE ========")
# x = sp.symbols('x:3')           # x: variable [x1,x2,x3]
# x0 = np.array([1.00,1.00,1.00]) # x0 = [x1=1,x2=1,x3=1]
# f = x[0]*x[2]+x[0]+1            # f = x1x3 + x1 + 1
# print(FD_multi(f, x0, x,0.1,2))        # df = [2,0,1]
print("======== EXP END ========")

x = sp.symbols('x:1')           
x0 = np.array([0.6]) 
f = -1*sp.ln(x[0])         
print(FD_multi_Error(f, x0, x,0.02,2)) 

======== EXAMPLE ========
======== EXP END ========
0.000617695800142037


In [ ]:
# Question 5: Finite Difference Gradient
# Finite Different Method
x = sp.symbols("x:3")
x0 = [1.00,1.00,1.00]
f = (x[0]**2)*x[1]+(x[0]**2)*(x[2]**2)+x[0]*(x[1]**2)*(x[2]**2)
# Frontward, method==0
FD_multi(f,x0,x,0.1,0)

array([5.20000000000000, 3.10000000000000, 4.20000000000000], dtype=object)

In [ ]:
# Attempt 2
# Question 8: Finite Difference Gradient
# Finite Different Method
x = sp.symbols("x:3")
x0 = [1.00,1.00,1.00]
f = (x[1]**2)*x[0]+(x[1]**2)*(x[2])+(x[1]**2)
# Backward, method==0
FD_multi(f,x0,x,0.1,1)

array([1.00000000000000, 5.70000000000000, 1.00000000000000], dtype=object)

In [ ]:
# Attempt 3
# Question 6: Finite Difference Gradient
# Finite Different Method
x = sp.symbols("x:3")
x0 = [1.00,1.00,1.00]
f = x[0]*x[1]*(x[2]**2)+2*x[1]*x[2]
# Backward, method==0
FD_multi(f,x0,x,0.1,2)

array([1.00000000000000, 3.00000000000000, 4.00000000000000], dtype=object)

In [ ]:
x = sp.symbols("x:1")
x0 = [0.2]
f = x[0]**2+10
# Backward, method==0
FD_multi(f,x0,x,0.01,0)

array([0.410000000000110], dtype=object)

In [ ]:
x = sp.symbols("x:1")
x0 = [0.4]
f = sp.exp(x[0])+10
# Backward, method==0
FD_multi(f,x0,x,0.06,0)

array([1.53748812255354], dtype=object)

In [ ]:
x = sp.symbols("x:1")
x0 = [0.5]
f = x[0]**2+10
FD_multi(f,x0,x,0.04,2)

array([1.00000000000000], dtype=object)