In [ ]:
import numpy as np
import scipy as sci
import scipy.sparse as sparse

# Get dense matrix from CSR data
def CSR_to_Dense(data, rowptr, col):
  A = sparse.csr_matrix((data, col, rowptr))
  print(A.toarray())
  print()
  return A.toarray()

# Get dense matrix from COO data
def COO_to_Dense(data, row, col):
  A = sparse.coo_matrix((data, (row, col)))
  print(A.toarray())
  print()
  return A.toarray()

# get CSR data from matrix A
def get_CSR(A):
  A_CSR = sparse.csr_matrix(A)
  data = A_CSR.data
  rowptr = A_CSR.indptr
  col = A_CSR.indices
  print("A.data   = "+ str(data))
  print("A.col    = "+ str(col))
  print("A.rowptr = "+ str(rowptr))
  print()
  return (A_CSR,data,rowptr,col)

# get COO data from matrix A
def get_COO(A):
  A_COO = sparse.coo_matrix(A)
  data = A_COO.data
  row = A_COO.row
  col = A_COO.col
  print("A.data   = "+ str(data))
  print("A.col    = "+ str(col))
  print("A.row = "+ str(row))
  print()
  return (A_COO,data,row,col)

# get the size of CSR or COO matrix
def get_storage(data_size, col_size, row_size, data_num, col_num, row_num):
  return data_size*data_num + col_size*col_num + row_size*row_num

# the matrix's shape is in (m,n)
# m = num of row, n = num of col
# dense_size is the storage size for one entry in dense matrix
def CSR_vs_dense(m,n,dense_size,CSR_col_size,CSR_row_size,CSR_data_size):
  total = m * n
  largest = 0
  dense_mem = total * dense_size
  for i in range(total+1):
    CSR_mem = CSR_row_size * (n + 1)
    CSR_mem += (i * (CSR_col_size + CSR_data_size))
    if(CSR_mem>=dense_mem):
      largest = i - 1
      break
  return largest

In [ ]:
# Construct a Matrix from CSR Format
data = [.30,.20,.80,.50,.90,.80,.80,.60]
row = [0,3,5,6,8]
col = [0,2,3,0,2,3,1,2]
A = CSR_to_Dense(data, row, col)
A_CSR = get_CSR(A)

[[0.3 0.  0.2 0.8]
 [0.5 0.  0.9 0. ]
 [0.  0.  0.  0.8]
 [0.  0.8 0.6 0. ]]

A.data   = [0.3 0.2 0.8 0.5 0.9 0.8 0.8 0.6]
A.col    = [0 2 3 0 2 3 1 2]
A.rowptr = [0 3 5 6 8]



In [ ]:
# CSR vs Dense format
CSR_vs_dense(130,130,4,4,4,4)

8384

In [ ]:
data = np.array([.70,.40,.10,.70,.90,.60,.60,.60])
row = np.array([2,2,1,1,0,0,3,3])
col = np.array([2,1,0,1,0,2,2,3])

COO_to_Dense(data, row, col)

[[0.9 0.  0.6 0. ]
 [0.1 0.7 0.  0. ]
 [0.  0.4 0.7 0. ]
 [0.  0.  0.6 0.6]]



array([[0.9, 0. , 0.6, 0. ],
       [0.1, 0.7, 0. , 0. ],
       [0. , 0.4, 0.7, 0. ],
       [0. , 0. , 0.6, 0.6]])

In [ ]:
A = sparse.coo_matrix([[1,2],[3,4]])
B = [[1,1],[0,1]]
A @ B

array([[1, 3],
       [3, 7]], dtype=int64)